Repository Pryaxis/TShock, pull requests merged in 2021-11, with the labels that each got.

#2488 Fix Linux guide
  CHANGELOG.md
  README.md
Labels: size/XS

#2450 Change default RespawnSeconds & RespawnBossSeconds from 10 to 0
  CHANGELOG.md
  TShockAPI/Configuration/TShockConfig.cs
Labels: size/S

#2419 Add colour differentiation and examples for more commands
  CHANGELOG.md
  TShockAPI/Commands.cs
  TShockAPI/TSPlayer.cs
  TShockAPI/Utils.cs
Labels: size/L

#2508 Fix invalid xml
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
  TShockAPI/TShock.cs
  TShockAPI/Utils.cs
Labels: size/S

#2447 The ability to change the player's pvp mode
  TShockAPI/TSPlayer.cs
Labels: size/S

#2513 Update new buffs for NPC
  CHANGELOG.md
  TShockAPI/Bouncer.cs
Labels: size/S

#2515 Added "Bouncer", which prohibits the creation of large projectiles.
  CHANGELOG.md
  TShockAPI/Bouncer.cs
  TShockAPI/GetDataHandlers.cs
Labels: size/M

#2518 Fixed the ability to spawn Zenith projectile with non-original items.
  CHANGELOG.md
  TShockAPI/Bouncer.cs
  TShockAPI/Configuration/TShockConfig.cs
Labels: size/S
