Repository Pryaxis/TShock, pull requests merged in 2021-08, with the labels that each got.

#2411 New config option for disabling Skeletron Prime bombs
  CHANGELOG.md
  TShockAPI/Configuration/TShockConfig.cs
  TShockAPI/TShock.cs
Labels: size/S

#2406 Improve login error messages and post-register process
  CHANGELOG.md
  TShockAPI/Commands.cs
Labels: size/S

#2412 Add ban usage examples + minor grammar & visual fixes for ban help
  CHANGELOG.md
  TShockAPI/Commands.cs
Labels: size/S

#2402 Add Lunatic Cultist summonboss permission check
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
Labels: size/S

#2398 Introduce `SoftcoreOnly` config option to allow only softcore characters to connect.
  CHANGELOG.md
  TShockAPI/Configuration/TShockConfig.cs
  TShockAPI/GetDataHandlers.cs
Labels: size/S

#2405 Add notify msg for online player group change
  CHANGELOG.md
  TShockAPI/Commands.cs
Labels: size/XS

#2416 Add new respawn command
  CHANGELOG.md
  TShockAPI/Commands.cs
  TShockAPI/Permissions.cs
Labels: size/M

#2417 Fix typo in ban usage examples
  TShockAPI/Commands.cs
Labels: size/XS

#2420 Return loopback IP if RealPlayer is false
  CHANGELOG.md
  TShockAPI/TSPlayer.cs
Labels: size/XS

#2397 Fix invalid group problems & error reporting on startup
  CHANGELOG.md
  TShockAPI/Commands.cs
  TShockAPI/DB/GroupManager.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/TShock.cs
Labels: size/M
