Repository Pryaxis/TShock, pull requests merged in 2021-12, with the labels that each got.

#2525 Added DataHandler for NpcTalk
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
Labels: size/M

#2526 Begin documentation of Terraria network protocol
  docs/Developer/Protocol Documentation.md
  docs/Developer/Protocol/Index.md
  docs/Developer/Protocol/Packets/Client UUID.md
  docs/Developer/Protocol/Packets/Connect Request.md
  docs/Developer/Protocol/Packets/Disconnect.md
  docs/Developer/Protocol/Packets/Modify Tile.md
  docs/Developer/Protocol/Packets/Player Active.md
  docs/Developer/Protocol/Packets/Player Death.md
  docs/Developer/Protocol/Packets/Player HP.md
  docs/Developer/Protocol/Packets/Player Hurt.md
  docs/Developer/Protocol/Packets/Player Info.md
  docs/Developer/Protocol/Packets/Player Item Animation.md
  docs/Developer/Protocol/Packets/Player Mana.md
  docs/Developer/Protocol/Packets/Set User Slot.md
  docs/Developer/Protocol/Packets/Spawn Data.md
  docs/Developer/Protocol/Packets/Sync Inventory Slot.md
  docs/Developer/Protocol/Packets/Tile Frame Section.md
  docs/Developer/Protocol/Packets/Tile Section.md
  docs/Developer/Protocol/Packets/Toggle PvP.md
  docs/Developer/Protocol/Packets/World Data.md
  docs/Developer/Protocol/Types/Color.md
  docs/Developer/Protocol/Types/Network Text.md
  docs/Developer/Protocol/Types/Player Death Reason.md
  docs/Developer/Protocol/Types/String.md
  docs/Developer/Slots.md
  docs/Developer/Tile Section.md
  docs/Developer/World File Format.md
Labels: size/XXL

#2521 Fixed exploit with cheaters ability to create custom death message
  CHANGELOG.md
  TShockAPI/Bouncer.cs
  TShockAPI/Configuration/TShockConfig.cs
Labels: size/S

#2529 Added the `OnSignRead` handler and `SignRead` event, and prevent out of bounds tile access
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
Labels: size/M

#2527 Added check to `HandleNpcTalk` to ensure the passed NPC index is within bounds
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
Labels: size/S

#2528 Corrected customDeathReason in OnPlayerDamage
  TShockAPI/Bouncer.cs
Labels: size/XS

#2534 Fixed rejection check inside of `HandlePaintTile` when using Paint Sprayer
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
  TShockAPI/TSPlayer.cs
Labels: size/S

#2535 Added hook for ReleaseNPC packet and anticheat for both catch and release npc
  CHANGELOG.md
  TShockAPI/Bouncer.cs
  TShockAPI/GetDataHandlers.cs
Labels: size/L

#2538 Turn packet list into table
  docs/Developer/Protocol/Index.md
Labels: size/L
