Repository Pryaxis/TShock, pull requests merged in 2022-12, with the labels that each got.

#2833 Fixed Super Sponge unable to absorb shimmer
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/L

#2857 Whitelist the Mighty Wind and Hellfire buffs
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/S

#2853 New Crowdin updates
  i18n/de_DE/TShockAPI.po
  i18n/en_PT/TShockAPI.po
  i18n/es_ES/TShockAPI.po
  i18n/fr_FR/TShockAPI.po
  i18n/fr_QC/TShockAPI.po
  i18n/id_ID/TShockAPI.po
  i18n/it_IT/TShockAPI.po
  i18n/ja_JP/TShockAPI.po
  i18n/pl_PL/TShockAPI.po
  i18n/pt_BR/TShockAPI.po
  i18n/pt_PT/TShockAPI.po
  i18n/ru_RU/TShockAPI.po
  i18n/ru_UA/TShockAPI.po
  i18n/tok/TShockAPI.po
  i18n/tr_TR/TShockAPI.po
  i18n/zh_CN/TShockAPI.po
Labels: size/XXL

#2852 Update GetDataHandlers.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/Net/SpawnMsg.cs
  TShockAPI/TSPlayer.cs
  docs/changelog.md
Labels: size/L

#2851 Pvp with no team
  TShockAPI/Configuration/TShockConfig.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/TShock.cs
  docs/changelog.md
Labels: size/S

#2865 New Crowdin updates
  i18n/de_DE/TShockAPI.po
  i18n/en_PT/TShockAPI.po
  i18n/es_ES/TShockAPI.po
  i18n/fr_FR/TShockAPI.po
  i18n/fr_QC/TShockAPI.po
  i18n/id_ID/TShockAPI.po
  i18n/it_IT/TShockAPI.po
  i18n/ja_JP/TShockAPI.po
  i18n/pl_PL/TShockAPI.po
  i18n/pt_BR/TShockAPI.po
  i18n/pt_PT/TShockAPI.po
  i18n/ru_RU/TShockAPI.po
  i18n/ru_UA/TShockAPI.po
  i18n/tok/TShockAPI.po
  i18n/tr_TR/TShockAPI.po
  i18n/zh_CN/TShockAPI.po
Labels: size/XXL

#2867 New Crowdin updates
  i18n/zh_CN/TShockAPI.po
Labels: size/M

#2872 Fixed startup error
  TShockLauncher/Program.cs
Labels: size/XS
