Repository Pryaxis/TShock, pull requests merged in 2022-02, with the labels that each got.

#2565 Remove extraneous space in README.
  CHANGELOG.md
  README.md
Labels: size/XS

#2552 Fix `TSPlayer.SendTileSquare` not being centered.
  CHANGELOG.md
  TShockAPI/Bouncer.cs
  TShockAPI/Commands.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/ItemBans.cs
  TShockAPI/RegionHandler.cs
  TShockAPI/TSPlayer.cs
  TShockAPI/TSServerPlayer.cs
Labels: size/L

#2400 Improved the `/grow` command to reduce code duplication, and allow easy future modification.
  CHANGELOG.md
  TShockAPI/Commands.cs
Labels: size/L

#2536 Remove monomod dev build shims
  .github/workflows/ci-otapi3.yml
  CHANGELOG.md
  appveyor.yml
Labels: size/L

#2522 Fix item dupe via /logout & NPC (#2495 issue)
  CHANGELOG.md
  TShockAPI/Commands.cs
Labels: followup-required, size/XS
