Repository Pryaxis/TShock, pull requests merged in 2022-10, with the labels that each got.

#2677 Use a string interpolation and escape single quotes when escaping tables
  CHANGELOG.md
  TShockAPI/DB/IQueryBuilder.cs
Labels: size/XS

#2680 Remove obsolete resources
  CHANGELOG.md
  TShockAPI/Resources.Designer.cs
  TShockAPI/Resources.resx
Labels: size/L

#2688 Fix #2674 - Change the use of current directory to match the server a…
  CHANGELOG.md
  TShockLauncher/Program.cs
Labels: size/XS

#2697 Fix hard/mediumcore ban on death when settings are enabled.
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
  TShockAPI/TSPlayer.cs
Labels: size/M

#2695 Don't allow players to sync loadout index whilst disabled
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
Labels: size/S

#2679 Fix auto-painting tile/wall being rejected from Hand of Creation
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
Labels: size/S

#2626 More robust parsing of large timespans (Fixes #2625)
  CHANGELOG.md
  TShockAPI/Commands.cs
  TShockAPI/Utils.cs
Labels: size/M

#2703 Fix player does't use the Shellphone (Ocean), Shellphone (Underworld)…
  CHANGELOG.md
  TShockAPI/GetDataHandlers.cs
Labels: size/M

#2706 Update Github CI to not tarball artifacts for Windows only
  .github/workflows/ci-otapi3.yml
  CHANGELOG.md
Labels: size/S

#2699 Allow Blood Butcherer and Shimmer buffs to be applied to NPCs by players
  CHANGELOG.md
  TShockAPI/Bouncer.cs
Labels: size/XS

#2722 Fix NetTile IndexOutOfRangeException
  CHANGELOG.md
  TShockAPI/Handlers/SendTileRectHandler.cs
  TShockAPI/Net/NetTile.cs
Labels: size/M

#2719 Fix Inferno Fork's OnFire debuff causing Bouncer reject abnormal buff
  CHANGELOG.md
  TShockAPI/Bouncer.cs
Labels: size/XS

#2724 Allow Cool Whip to apply `CoolWhipNPCDebuff`, fixing Bouncer rejects
  CHANGELOG.md
  TShockAPI/Bouncer.cs
Labels: size/XS

#2656 [Dub] Prevent server broadcast to accept an empty message
  CHANGELOG.md
  TShockAPI/Commands.cs
Labels: size/S

#2717 Fix Bottomless Honey Bucket being rejected, and reject Shimmer placement without bucket
  CHANGELOG.md
  TShockAPI/Bouncer.cs
  TShockAPI/GetDataHandlers.cs
Labels: size/M

#2621 Fixed Bouncer possibly rejecting Explosive Bunny critter releases
  CHANGELOG.md
  TShockAPI/Bouncer.cs
Labels: size/M

#2716 Allow some new tile interactions to succeed in Bouncer
  CHANGELOG.md
  TShockAPI/Bouncer.cs
Labels: size/M

#2453 Fix player buffs applied to other players through `PlayerAddBuff` packet
  CHANGELOG.md
  TShockAPI/Bouncer.cs
  TShockAPI/GetDataHandlers.cs
Labels: size/L

#2728 Start to update documentation
  README.md
  TShockAPI/Utils.cs
  docs/.nojekyll
  docs/CNAME
  docs/README.md
  docs/_sidebar.md
  docs/changelog.md
  docs/command-line-parameters.md
  docs/index.html
  docs/tile-providers.md
Labels: size/L

#2731 Fix grass mowing keeping hanging vines intact
  TShockAPI/Handlers/SendTileRectHandler.cs
  docs/changelog.md
Labels: size/XS

#2733 Add localization support for console spam reduction
  TShockAPI/Modules/ReduceConsoleSpam.cs
  docs/changelog.md
Labels: size/S

#2734 Update the cn version of readme
  README_cn.md
Labels: size/L

#2736 Add i18n system
  .github/scripts/check-diff.py
  .github/scripts/i18n.sh
  .github/workflows/ci-otapi3.yml
  .github/workflows/i18n-extract.yml
  TShockAPI/Commands.cs
  TShockAPI/I18n.cs
  TShockAPI/TShockAPI.csproj
  TShockLauncher/TShockLauncher.csproj
  i18n/.gitkeep
  i18n/template.pot
  i18n/tok/TShockAPI.po
Labels: size/L

#2737 Use global using static for ICatalog methods
  TShockAPI/Commands.cs
  TShockAPI/I18n.cs
  docs/i18n.md
Labels: size/L

#2743 Some i18nifiying
  TShockAPI/BackupManager.cs
  TShockAPI/Bouncer.cs
  TShockAPI/DB/BanManager.cs
  TShockAPI/DB/CharacterManager.cs
  TShockAPI/DB/GroupManager.cs
  TShockAPI/DB/IQueryBuilder.cs
  TShockAPI/DB/ProjectileManager.cs
  TShockAPI/DB/RegionManager.cs
  TShockAPI/DB/ResearchDatastore.cs
  TShockAPI/DB/TileManager.cs
  TShockAPI/DB/UserManager.cs
  TShockAPI/Extensions/DbExt.cs
  TShockAPI/Handlers/DisplayDollItemSyncHandler.cs
  TShockAPI/Handlers/EmojiHandler.cs
  TShockAPI/Handlers/IllegalPerSe/EmojiPlayerMismatch.cs
  TShockAPI/Handlers/LandGolfBallInCupHandler.cs
  TShockAPI/Handlers/NetModules/CreativePowerHandler.cs
  TShockAPI/Handlers/NetModules/CreativeUnlocksHandler.cs
  TShockAPI/Handlers/NetModules/PylonHandler.cs
  TShockAPI/Handlers/RequestTileEntityInteractionHandler.cs
  TShockAPI/Handlers/SendTileRectHandler.cs
  TShockAPI/Handlers/SyncTilePickingHandler.cs
  TShockAPI/ILog.cs
  TShockAPI/Modules/ModuleManager.cs
  TShockAPI/Net/BaseMsg.cs
  TShockAPI/Rest/Rest.cs
  TShockAPI/Rest/RestCommand.cs
  TShockAPI/Rest/RestManager.cs
  TShockAPI/Rest/SecureRest.cs
  TShockAPI/SqlLog.cs
  TShockAPI/TextLog.cs
Labels: size/XL

#2745 i18nify commands
  TShockAPI/Commands.cs
  TShockAPI/PaginationTools.cs
Labels: size/L

#2746 New Crowdin updates
  i18n/de_DE/TShockAPI.po
  i18n/es_ES/TShockAPI.po
  i18n/fr_FR/TShockAPI.po
  i18n/fr_QC/TShockAPI.po
  i18n/ja_JP/TShockAPI.po
  i18n/ru_RU/TShockAPI.po
  i18n/ru_UA/TShockAPI.po
  i18n/tok/TShockAPI.po
  i18n/tr_TR/TShockAPI.po
  i18n/zh_CN/TShockAPI.po
Labels: size/XXL

#2747 Include geoip.dat file again
  TShockLauncher/TShockLauncher.csproj
  docs/changelog.md
Labels: size/S

#2675 Introduce loadout support (with SSC)
  TShockAPI/Commands.cs
  TShockAPI/DB/CharacterManager.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/NetItem.cs
  TShockAPI/PlayerData.cs
  TShockAPI/TSPlayer.cs
  TShockAPI/TShock.cs
  docs/changelog.md
Labels: size/L

#2749 Fix flamethrowers kicking players
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/XS

#2751 Fix being kicked for using the new sponge types
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/S

#2753 Update Bouncer / OnNPCAddBuff
  TShockAPI/Bouncer.cs
  TShockAPI/Permissions.cs
  TShockAPI/Utils.cs
  docs/changelog.md
  docs/permission-descriptions.md
Labels: size/M

#2760 Update i18n
  TShockAPI/Bouncer.cs
  TShockAPI/Commands.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/ItemBans.cs
  TShockAPI/PaginationTools.cs
  TShockAPI/RegionHandler.cs
  TShockAPI/Rest/RestManager.cs
  TShockAPI/SaveManager.cs
  TShockAPI/SqlLog.cs
  TShockAPI/TSPlayer.cs
  TShockAPI/TShock.cs
  TShockAPI/UpdateManager.cs
  TShockAPI/Utils.cs
Labels: size/XXL

#2756 New Crowdin updates
  i18n/de_DE/TShockAPI.po
  i18n/en_PT/TShockAPI.po
  i18n/es_ES/TShockAPI.po
  i18n/fr_FR/TShockAPI.po
  i18n/fr_QC/TShockAPI.po
  i18n/ja_JP/TShockAPI.po
  i18n/ru_RU/TShockAPI.po
  i18n/ru_UA/TShockAPI.po
  i18n/tok/TShockAPI.po
  i18n/tr_TR/TShockAPI.po
  i18n/zh_CN/TShockAPI.po
Labels: size/XXL

#2765 Minor i18n fix with interpolation
  TShockAPI/Commands.cs
  TShockAPI/GetDataHandlers.cs
Labels: size/S

#2748 Dockerize TShock
  .dockerignore
  Dockerfile
  docs/_sidebar.md
  docs/changelog.md
  docs/docker.md
Labels: size/L

#2754 Handle vanilla `-lang` and `-language` CLI flags for I18n
  TShockAPI/I18n.cs
  docs/changelog.md
Labels: size/S

#2758 Fixed SSC not save `ateArtisanBread`, `usedAegisCrystal`, `usedAegisFruit`, `usedArcaneCrystal`, `usedGalaxyPearl`, `usedGummyWorm`, `usedAmbrosia`, `unlockedSuperCart`, `enabledSuperCart` flags, and Server will correct read them.
  TShockAPI/DB/CharacterManager.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/PlayerData.cs
  docs/changelog.md
Labels: size/L

#2762 New Crowdin updates
  i18n/de_DE/TShockAPI.po
  i18n/en_PT/TShockAPI.po
  i18n/es_ES/TShockAPI.po
  i18n/fr_FR/TShockAPI.po
  i18n/fr_QC/TShockAPI.po
  i18n/ja_JP/TShockAPI.po
  i18n/ru_RU/TShockAPI.po
  i18n/ru_UA/TShockAPI.po
  i18n/tok/TShockAPI.po
  i18n/tr_TR/TShockAPI.po
  i18n/zh_CN/TShockAPI.po
Labels: size/XXL

#2769 Fix i18n not calling actual method
  TShockAPI/I18n.cs
Labels: size/S

#2782 Show buff time in the log
  TShockAPI/Bouncer.cs
Labels: size/XS

#2781 Hide command args when not DoLog
  TShockAPI/Commands.cs
  docs/changelog.md
Labels: size/XS
