Repository Pryaxis/TShock, pull requests merged in 2022-11, with the labels that each got.

#2784 Fix item giving
  TShockAPI/TSPlayer.cs
  docs/changelog.md
Labels: size/XS

#2787 Geoip exclude
  TShockLauncher/TShockLauncher.csproj
  docs/changelog.md
Labels: size/XS

#2793 fix docker docs for changes in Dockerfile
  docs/docker.md
Labels: size/XS

#2794 fix docker example code
  docs/docker.md
Labels: size/XS

#2801 Fix #2800
  TShockAPI/Handlers/SendTileRectHandler.cs
Labels: size/XS

#2795 Allow Surly Slime to be fished
  TShockAPI/GetDataHandlers.cs
  docs/changelog.md
Labels: size/XS

#2813 New Crowdin updates
  i18n/en_PT/TShockAPI.po
  i18n/pt_BR/TShockAPI.po
  i18n/ru_RU/TShockAPI.po
  i18n/zh_CN/TShockAPI.po
Labels: size/XXL

#2808 Update HandleSpawnBoss
  TShockAPI/GetDataHandlers.cs
  docs/changelog.md
Labels: size/S

#2790 More i18n
  TShockAPI/Bouncer.cs
  TShockAPI/Commands.cs
  TShockAPI/Configuration/ServerSideConfig.cs
  TShockAPI/Configuration/TShockConfig.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/Handlers/SendTileRectHandler.cs
  TShockAPI/ItemBans.cs
  TShockAPI/Permissions.cs
  TShockAPI/Rest/RestManager.cs
  TShockAPI/TSPlayer.cs
  TShockAPI/TSServerPlayer.cs
  TShockAPI/TShock.cs
  TShockAPI/UpdateManager.cs
Labels: size/L

#2811 Allow Torch God's Facor to place biome torch and campfire
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/S

#2791 Use same logic for all GetByNameOrId
  TShockAPI/Localization/EnglishLanguage.cs
  TShockAPI/Utils.cs
  docs/changelog.md
Labels: size/L

#2848 Fix Utils.GetByName add duplicate candidate for same target i18n
  TShockAPI/Utils.cs
Labels: size/M

#2827 Add Shadow Candle and Brain of Confusion to `PlayerAddBuffWhitelist`, improve rejection messages
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/M

#2832 Add WorldTileProvider to tshock config
  TShockAPI/Configuration/TShockConfig.cs
  TShockAPI/TShock.cs
  docs/changelog.md
Labels: size/S

#2839 Fix Digging Molecart and Bomb Fish blocked
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/S

#2840 Add tshock installer executable
  .github/workflows/ci-otapi3.yml
  TShock.sln
  TShockInstaller/Program.cs
  TShockInstaller/TShockInstaller.csproj
Labels: size/L

#2824 New Crowdin updates
  i18n/de_DE/TShockAPI.po
  i18n/en_PT/TShockAPI.po
  i18n/es_ES/TShockAPI.po
  i18n/fr_FR/TShockAPI.po
  i18n/fr_QC/TShockAPI.po
  i18n/id_ID/TShockAPI.po
  i18n/it_IT/TShockAPI.po
  i18n/ja_JP/TShockAPI.po
  i18n/pl_PL/TShockAPI.po
  i18n/pt_BR/TShockAPI.po
  i18n/pt_PT/TShockAPI.po
  i18n/ru_RU/TShockAPI.po
  i18n/ru_UA/TShockAPI.po
  i18n/tok/TShockAPI.po
  i18n/tr_TR/TShockAPI.po
  i18n/zh_CN/TShockAPI.po
Labels: size/XXL
