Repository Pryaxis/TShock, pull requests merged in 2024-04, with the labels that each got.

#3023 Lazy initialize TextLog._logWriter
  TShockAPI/TextLog.cs
  docs/changelog.md
Labels: size/S

#2974 Add CI for Docker images
  .github/workflows/ci-docker.yml
  Dockerfile
  docs/changelog.md
  docs/docker.md
Labels: size/M

#3029 Increase Cursed Inferno Maximum Debuff Time
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/XS
