Repository Pryaxis/TShock, pull requests merged in 2025-03, with the labels that each got.

#3064 fix(GetDataHandlers): handle and ignore `NpcItemStrike(msgid 24)`
  TShockAPI/GetDataHandlers.cs
  docs/changelog.md
Labels: size/XS

#3060 Bounce infinite or NaN player, projectile, or item velocity / position
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/M

#3031 Rewrite: Partially fix bed spawning for SSC
  TShockAPI/GetDataHandlers.cs
  TShockAPI/PlayerData.cs
  TShockAPI/TSPlayer.cs
  TShockAPI/TShock.cs
  docs/changelog.md
Labels: size/L

#2946 PlayerData changes
  TShockAPI/DB/CharacterManager.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/PlayerData.cs
  TShockAPI/TSPlayer.cs
  docs/changelog.md
Labels: size/M

#3027 Add permission for Moondial and unrecognized SFX
  TShockAPI/GetDataHandlers.cs
  TShockAPI/Permissions.cs
  docs/changelog.md
Labels: size/M

#2874 Seed initial group database with `default` and `guest` names from config
  TShockAPI/DB/GroupManager.cs
Labels: size/XS

#3067 Fix some confusion introduced by 98eed42 and b184133
  TShockAPI/DB/CharacterManager.cs
  TShockAPI/DB/GroupManager.cs
  TShockAPI/GetDataHandlers.cs
  TShockAPI/Permissions.cs
Labels: size/S

#3074 fix(Bouncer/SendTileRectHandler): two typos which causes incorrect validating range
  TShockAPI/Handlers/SendTileRectHandler.cs
Labels: size/XS

#3076 Fix Pryaxis/TShock#3073
  TShockAPI/Bouncer.cs
Labels: size/XS
