Repository Pryaxis/TShock, pull requests merged in 2025-01, with the labels that each got.

#2943 Fix dump-reference-data mutate command name
  TShockAPI/Permissions.cs
  docs/changelog.md
Labels: size/S

#3048 docker: Publish Docker images to GHCR
  .github/workflows/ci-docker.yml
  docs/changelog.md
  docs/docker.md
Labels: size/M

#2939 Use same TSPlayer.Active check
  TShockAPI/Bouncer.cs
  TShockAPI/Commands.cs
  TShockAPI/Rest/RestManager.cs
  TShockAPI/Utils.cs
  docs/changelog.md
Labels: size/S

#2925 Remove Connection: Close for REST api
  TShockAPI/Rest/Rest.cs
  docs/changelog.md
Labels: size/XS

#3005 Whitelist the Striking Moment (`ParryDamageBuff`) buff
  TShockAPI/Bouncer.cs
  docs/changelog.md
Labels: size/XS

#2945 NetItem changes
  TShockAPI/NetItem.cs
  docs/changelog.md
Labels: size/M

#3039 fix: /help, /me, and /p commands can't work in non-English languages
  TShockAPI/Localization/EnglishLanguage.cs
  TShockAPI/TShock.cs
  docs/changelog.md
Labels: size/M

#3015 fix: off no save command
  TShockAPI/Commands.cs
Labels: size/XS

#2947 Added AccountGroupUpdate hook, when trying to change a user group.
  TShockAPI/Commands.cs
  TShockAPI/DB/UserManager.cs
  TShockAPI/Hooks/AccountHooks.cs
  TShockAPI/Rest/RestManager.cs
  docs/changelog.md
Labels: size/L

#3055 Fix #2895
  TShockPluginManager/Nuget.cs
Labels: size/S

#3056 Automatic language detection
  TShockAPI/I18n.cs
Labels: size/XS

#3057 Detect xterm compatibility to avoid console spam
  TShockAPI/Utils.cs
Labels: size/XS

#2952 Ensure `TSPlayer.PlayerData` is non-null whilst syncing loadouts
  TShockAPI/GetDataHandlers.cs
  docs/changelog.md
Labels: size/XS

#2951 Group changes
  TShockAPI/Group.cs
  docs/changelog.md
Labels: size/M

#2960 New two hooks PrePlayerCommand and PostPlayerCommand
  TShockAPI/Commands.cs
  TShockAPI/Hooks/PlayerHooks.cs
  docs/changelog.md
Labels: size/L

#2882 Detect invalid TShock installations
  TShockLauncher/Program.cs
  docs/changelog.md
Labels: size/S
