Repository Pryaxis/TShock, pull requests merged in 2025-05, with the labels that each got.

#3097 Fix console title not updating and world not saving when the last player disconnects
  TShockAPI/TShock.cs
Labels: size/XS

#3095 feat: Add spawning pets perm to default group
  TShockAPI/DB/GroupManager.cs
Labels: size/XS

#3092 Feat: Add Postgres database support + Refactor database handling
  TShockAPI/Configuration/TShockConfig.cs
  TShockAPI/DB/BanManager.cs
  TShockAPI/DB/CharacterManager.cs
  TShockAPI/DB/DbBuilder.cs
  TShockAPI/DB/GroupManager.cs
  TShockAPI/DB/IQueryBuilder.cs
  TShockAPI/DB/ItemManager.cs
  TShockAPI/DB/ProjectileManager.cs
  TShockAPI/DB/Queries/GenericQueryBuilder.cs
  TShockAPI/DB/Queries/IQueryBuilder.cs
  TShockAPI/DB/Queries/MysqlQueryBuilder.cs
  TShockAPI/DB/Queries/PostgresQueryBuilder.cs
  TShockAPI/DB/Queries/SqliteQueryBuilder.cs
  TShockAPI/DB/RegionManager.cs
  TShockAPI/DB/RememberedPosManager.cs
  TShockAPI/DB/ResearchDatastore.cs
  TShockAPI/DB/SqlTable.cs
  TShockAPI/DB/SqlValue.cs
  TShockAPI/DB/TileManager.cs
  TShockAPI/DB/UserManager.cs
  TShockAPI/DB/WarpsManager.cs
  TShockAPI/Extensions/DbExt.cs
  TShockAPI/Extensions/StringExt.cs
  TShockAPI/SqlLog.cs
  TShockAPI/TShock.cs
  TShockAPI/TShockAPI.csproj
  TShockLauncher/TShockLauncher.csproj
Labels: size/XXL

#3088 Fix losing a item in ItemFrame upon interacting it on protected region you do not have access
  TShockAPI/Bouncer.cs
Labels: size/XS

#3082 fix(SendTileRectHandler): unable to place LogicSensors
  TShockAPI/Handlers/SendTileRectHandler.cs
Labels: size/XS

#3099 fix(OnTileEdit): item disappeared when hitting an ItemFrame without permission
  TShockAPI/Bouncer.cs
Labels: size/S

#3106 Allow for reloading of player bans
  TShockAPI/DB/BanManager.cs
  TShockAPI/Utils.cs
Labels: size/S
